spring:
  application:
    name: auth-service

  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5433/auth_db}
    username: ${AUTH_DB_USERNAME:decisify}
    password: ${AUTH_DB_PASSWORD:decisify_local}
    driver-class-name: org.postgresql.Driver
  
  jpa: 
    hibernate: 
      ddl-auto: validate

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

server:
  port: 8081